FROM    node:16-bullseye

RUN     apt-get update && apt-get -y upgrade

# NodeJS gm library depends on imagemagick
RUN     apt-get -y install imagemagick

COPY    ./docker-entrypoint.dev.sh /docker-entrypoint.sh

WORKDIR /usr/app

CMD     [ "sh", "/docker-entrypoint.sh" ]